// Lesson curriculum: progressive C# / Unity MonoBehaviour typing course.
// Each lesson has a title, a Hebrew description, and an array of code lines to type.
// Lines preserve real indentation (4 spaces per level) so muscle memory transfers to a real IDE.

const LESSONS = [
  {
    id: 1,
    title: "שלב 1 — סימני פיסוק וסוגריים",
    description: "התרגלות לסימנים הנפוצים ביותר בקוד C#: סוגריים, נקודה-פסיק, נקודה.",
    lines: [
      "{ }",
      "( )",
      "[ ]",
      "< >",
      ";",
      "{ ; }",
      "( ) { }",
      "a.b.c;",
      "x = 1;",
      "x == 1;",
      "x != 1;",
      "x += 1;",
      "x -= 1;",
      "x++;",
      "x--;",
      "a && b;",
      "a || b;",
      "!a;",
    ],
  },
  {
    id: 2,
    title: "שלב 2 — משתנים וטיפוסים",
    description: "הצהרות משתנים בסיסיות עם הטיפוסים הנפוצים ב-C#.",
    lines: [
      "int health = 100;",
      "float speed = 5.0f;",
      "bool isAlive = true;",
      "string playerName = \"Zion\";",
      "var score = 0;",
      "double gravity = 9.81;",
      "const int maxLives = 3;",
      "private int ammoCount = 30;",
      "public float jumpForce = 8f;",
      "[SerializeField] private int level;",
    ],
  },
  {
    id: 3,
    title: "שלב 3 — שלד של MonoBehaviour",
    description: "המבנה הבסיסי של כל סקריפט ביוניטי.",
    lines: [
      "using UnityEngine;",
      "",
      "public class PlayerController : MonoBehaviour",
      "{",
      "    void Start()",
      "    {",
      "    }",
      "",
      "    void Update()",
      "    {",
      "    }",
      "}",
    ],
  },
  {
    id: 4,
    title: "שלב 4 — מתודות מחזור החיים של יוניטי",
    description: "Awake, Start, Update, FixedUpdate ועוד — בסדר הנכון.",
    lines: [
      "void Awake()",
      "{",
      "    Debug.Log(\"Awake called\");",
      "}",
      "",
      "void OnEnable()",
      "{",
      "}",
      "",
      "void Start()",
      "{",
      "}",
      "",
      "void FixedUpdate()",
      "{",
      "}",
      "",
      "void LateUpdate()",
      "{",
      "}",
      "",
      "void OnDisable()",
      "{",
      "}",
      "",
      "void OnDestroy()",
      "{",
      "}",
    ],
  },
  {
    id: 5,
    title: "שלב 5 — Transform ו-Vector3",
    description: "תנועה בסיסית של אובייקטים במרחב התלת-מימדי.",
    lines: [
      "transform.position = Vector3.zero;",
      "transform.position += Vector3.forward;",
      "transform.Translate(Vector3.up * speed);",
      "transform.rotation = Quaternion.identity;",
      "transform.Rotate(0f, 90f, 0f);",
      "Vector3 direction = new Vector3(1, 0, 0);",
      "transform.localScale = Vector3.one * 2f;",
      "transform.LookAt(target);",
    ],
  },
  {
    id: 6,
    title: "שלב 6 — קלט מהשחקן (Input)",
    description: "קריאת מקשים, צירים ולחיצות עכבר.",
    lines: [
      "float h = Input.GetAxis(\"Horizontal\");",
      "float v = Input.GetAxis(\"Vertical\");",
      "if (Input.GetKeyDown(KeyCode.Space))",
      "{",
      "    Jump();",
      "}",
      "if (Input.GetMouseButtonDown(0))",
      "{",
      "    Shoot();",
      "}",
      "Vector3 move = new Vector3(h, 0, v) * speed * Time.deltaTime;",
    ],
  },
  {
    id: 7,
    title: "שלב 7 — GetComponent ורכיבים",
    description: "גישה לרכיבים אחרים על אותו GameObject.",
    lines: [
      "Rigidbody rb = GetComponent<Rigidbody>();",
      "Animator anim = GetComponent<Animator>();",
      "rb.AddForce(Vector3.up * jumpForce, ForceMode.Impulse);",
      "anim.SetBool(\"isRunning\", true);",
      "anim.SetTrigger(\"Attack\");",
      "if (TryGetComponent<Collider>(out Collider col))",
      "{",
      "    col.enabled = false;",
      "}",
    ],
  },
  {
    id: 8,
    title: "שלב 8 — פיזיקה והתנגשויות",
    description: "OnCollisionEnter, OnTriggerEnter ועבודה עם תגיות.",
    lines: [
      "void OnTriggerEnter(Collider other)",
      "{",
      "    if (other.CompareTag(\"Enemy\"))",
      "    {",
      "        TakeDamage(10);",
      "    }",
      "}",
      "",
      "void OnCollisionEnter(Collision collision)",
      "{",
      "    Debug.Log(collision.gameObject.name);",
      "}",
    ],
  },
  {
    id: 9,
    title: "שלב 9 — Coroutines",
    description: "פעולות אסינכרוניות מבוססות זמן בסטייל יוניטי.",
    lines: [
      "IEnumerator RespawnAfterDelay(float delay)",
      "{",
      "    yield return new WaitForSeconds(delay);",
      "    gameObject.SetActive(true);",
      "}",
      "",
      "void Die()",
      "{",
      "    StartCoroutine(RespawnAfterDelay(3f));",
      "}",
    ],
  },
  {
    id: 10,
    title: "שלב 10 — סקריפט שלם: PlayerController",
    description: "כתיבת סקריפט מלא של תנועת שחקן ב-Unity.",
    lines: [
      "using UnityEngine;",
      "",
      "public class PlayerController : MonoBehaviour",
      "{",
      "    public float speed = 5f;",
      "    public float jumpForce = 8f;",
      "    private Rigidbody rb;",
      "",
      "    void Awake()",
      "    {",
      "        rb = GetComponent<Rigidbody>();",
      "    }",
      "",
      "    void Update()",
      "    {",
      "        float h = Input.GetAxis(\"Horizontal\");",
      "        float v = Input.GetAxis(\"Vertical\");",
      "        Vector3 move = new Vector3(h, 0, v) * speed;",
      "        transform.Translate(move * Time.deltaTime);",
      "",
      "        if (Input.GetKeyDown(KeyCode.Space))",
      "        {",
      "            rb.AddForce(Vector3.up * jumpForce, ForceMode.Impulse);",
      "        }",
      "    }",
      "}",
    ],
  },
  {
    id: 11,
    title: "שלב 11 — סקריפט שלם: Health & Enemy",
    description: "מערכת חיים, נזק ומוות עם אירועים.",
    lines: [
      "using UnityEngine;",
      "using System;",
      "",
      "public class Health : MonoBehaviour",
      "{",
      "    public int maxHealth = 100;",
      "    private int currentHealth;",
      "    public event Action OnDeath;",
      "",
      "    void Start()",
      "    {",
      "        currentHealth = maxHealth;",
      "    }",
      "",
      "    public void TakeDamage(int amount)",
      "    {",
      "        currentHealth -= amount;",
      "        if (currentHealth <= 0)",
      "        {",
      "            OnDeath?.Invoke();",
      "            Destroy(gameObject);",
      "        }",
      "    }",
      "}",
    ],
  },
];
