// Lesson curriculum: progressive C# / Unity MonoBehaviour typing course.
// Each lesson has a title, a Hebrew description, and an array of code lines to type.
// Lines preserve real indentation (4 spaces per level) so muscle memory transfers to a real IDE.

const LESSONS = [
  {
    id: 1,
    title: "שלב 1 — סימני פיסוק וסוגריים",
    description: "התרגלות לסימנים הנפוצים ביותר בקוד C#: סוגריים, נקודה-פסיק, נקודה.",
    lines: [
      "{ }",
      "( )",
      "[ ]",
      "< >",
      ";",
      "{ ; }",
      "( ) { }",
      "a.b.c;",
      "x = 1;",
      "x == 1;",
      "x != 1;",
      "x += 1;",
      "x -= 1;",
      "x++;",
      "x--;",
      "a && b;",
      "a || b;",
      "!a;",
    ],
  },
  {
    id: 2,
    title: "שלב 2 — משתנים וטיפוסים",
    description: "הצהרות משתנים בסיסיות עם הטיפוסים הנפוצים ב-C#.",
    lines: [
      "int health = 100;",
      "float speed = 5.0f;",
      "bool isAlive = true;",
      "string playerName = \"Zion\";",
      "var score = 0;",
      "double gravity = 9.81;",
      "const int maxLives = 3;",
      "private int ammoCount = 30;",
      "public float jumpForce = 8f;",
      "[SerializeField] private int level;",
    ],
  },
  {
    id: 3,
    title: "שלב 3 — שלד של MonoBehaviour",
    description: "המבנה הבסיסי של כל סקריפט ביוניטי.",
    lines: [
      "using UnityEngine;",
      "",
      "public class PlayerController : MonoBehaviour",
      "{",
      "    void Start()",
      "    {",
      "    }",
      "",
      "    void Update()",
      "    {",
      "    }",
      "}",
    ],
  },
  {
    id: 4,
    title: "שלב 4 — מתודות מחזור החיים של יוניטי",
    description: "Awake, Start, Update, FixedUpdate ועוד — בסדר הנכון.",
    lines: [
      "void Awake()",
      "{",
      "    Debug.Log(\"Awake called\");",
      "}",
      "",
      "void OnEnable()",
      "{",
      "}",
      "",
      "void Start()",
      "{",
      "}",
      "",
      "void FixedUpdate()",
      "{",
      "}",
      "",
      "void LateUpdate()",
      "{",
      "}",
      "",
      "void OnDisable()",
      "{",
      "}",
      "",
      "void OnDestroy()",
      "{",
      "}",
    ],
  },
  {
    id: 5,
    title: "שלב 5 — Transform ו-Vector3",
    description: "תנועה בסיסית של אובייקטים במרחב התלת-מימדי.",
    lines: [
      "transform.position = Vector3.zero;",
      "transform.position += Vector3.forward;",
      "transform.Translate(Vector3.up * speed);",
      "transform.rotation = Quaternion.identity;",
      "transform.Rotate(0f, 90f, 0f);",
      "Vector3 direction = new Vector3(1, 0, 0);",
      "transform.localScale = Vector3.one * 2f;",
      "transform.LookAt(target);",
    ],
  },
  {
    id: 6,
    title: "שלב 6 — קלט מהשחקן (Input)",
    description: "קריאת מקשים, צירים ולחיצות עכבר.",
    lines: [
      "float h = Input.GetAxis(\"Horizontal\");",
      "float v = Input.GetAxis(\"Vertical\");",
      "if (Input.GetKeyDown(KeyCode.Space))",
      "{",
      "    Jump();",
      "}",
      "if (Input.GetMouseButtonDown(0))",
      "{",
      "    Shoot();",
      "}",
      "Vector3 move = new Vector3(h, 0, v) * speed * Time.deltaTime;",
    ],
  },
  {
    id: 7,
    title: "שלב 7 — GetComponent ורכיבים",
    description: "גישה לרכיבים אחרים על אותו GameObject.",
    lines: [
      "Rigidbody rb = GetComponent<Rigidbody>();",
      "Animator anim = GetComponent<Animator>();",
      "rb.AddForce(Vector3.up * jumpForce, ForceMode.Impulse);",
      "anim.SetBool(\"isRunning\", true);",
      "anim.SetTrigger(\"Attack\");",
      "if (TryGetComponent<Collider>(out Collider col))",
      "{",
      "    col.enabled = false;",
      "}",
    ],
  },
  {
    id: 8,
    title: "שלב 8 — פיזיקה והתנגשויות",
    description: "OnCollisionEnter, OnTriggerEnter ועבודה עם תגיות.",
    lines: [
      "void OnTriggerEnter(Collider other)",
      "{",
      "    if (other.CompareTag(\"Enemy\"))",
      "    {",
      "        TakeDamage(10);",
      "    }",
      "}",
      "",
      "void OnCollisionEnter(Collision collision)",
      "{",
      "    Debug.Log(collision.gameObject.name);",
      "}",
    ],
  },
  {
    id: 9,
    title: "שלב 9 — Coroutines",
    description: "פעולות אסינכרוניות מבוססות זמן בסטייל יוניטי.",
    lines: [
      "IEnumerator RespawnAfterDelay(float delay)",
      "{",
      "    yield return new WaitForSeconds(delay);",
      "    gameObject.SetActive(true);",
      "}",
      "",
      "void Die()",
      "{",
      "    StartCoroutine(RespawnAfterDelay(3f));",
      "}",
    ],
  },
  {
    id: 10,
    title: "שלב 10 — סקריפט שלם: PlayerController",
    description: "כתיבת סקריפט מלא של תנועת שחקן ב-Unity.",
    lines: [
      "using UnityEngine;",
      "",
      "public class PlayerController : MonoBehaviour",
      "{",
      "    public float speed = 5f;",
      "    public float jumpForce = 8f;",
      "    private Rigidbody rb;",
      "",
      "    void Awake()",
      "    {",
      "        rb = GetComponent<Rigidbody>();",
      "    }",
      "",
      "    void Update()",
      "    {",
      "        float h = Input.GetAxis(\"Horizontal\");",
      "        float v = Input.GetAxis(\"Vertical\");",
      "        Vector3 move = new Vector3(h, 0, v) * speed;",
      "        transform.Translate(move * Time.deltaTime);",
      "",
      "        if (Input.GetKeyDown(KeyCode.Space))",
      "        {",
      "            rb.AddForce(Vector3.up * jumpForce, ForceMode.Impulse);",
      "        }",
      "    }",
      "}",
    ],
  },
  {
    id: 11,
    title: "שלב 11 — סקריפט שלם: Health & Enemy",
    description: "מערכת חיים, נזק ומוות עם אירועים.",
    lines: [
      "using UnityEngine;",
      "using System;",
      "",
      "public class Health : MonoBehaviour",
      "{",
      "    public int maxHealth = 100;",
      "    private int currentHealth;",
      "    public event Action OnDeath;",
      "",
      "    void Start()",
      "    {",
      "        currentHealth = maxHealth;",
      "    }",
      "",
      "    public void TakeDamage(int amount)",
      "    {",
      "        currentHealth -= amount;",
      "        if (currentHealth <= 0)",
      "        {",
      "            OnDeath?.Invoke();",
      "            Destroy(gameObject);",
      "        }",
      "    }",
      "}",
    ],
  },
  {
    id: 12,
    title: "שלב 12 — Animator מתקדם",
    description: "פרמטרים של Animator: SetFloat, CrossFade ואירועי אנימציה.",
    lines: [
      "anim.SetFloat(\"Speed\", currentSpeed);",
      "anim.SetFloat(\"Speed\", currentSpeed, 0.1f, Time.deltaTime);",
      "anim.SetBool(\"IsGrounded\", isGrounded);",
      "anim.SetInteger(\"ComboIndex\", comboIndex);",
      "anim.CrossFade(\"Attack\", 0.15f);",
      "anim.Play(\"Idle\", 0);",
      "if (anim.GetCurrentAnimatorStateInfo(0).IsName(\"Jump\"))",
      "{",
      "    anim.applyRootMotion = true;",
      "}",
      "",
      "void OnFootstep(AnimationEvent evt)",
      "{",
      "    AudioSource.PlayClipAtPoint(footstepClip, transform.position);",
      "}",
    ],
  },
  {
    id: 13,
    title: "שלב 13 — CharacterController",
    description: "תנועה מבוססת קפסולה עם בדיקת קרקע וכבידה.",
    lines: [
      "using UnityEngine;",
      "",
      "[RequireComponent(typeof(CharacterController))]",
      "public class PlayerMotor : MonoBehaviour",
      "{",
      "    public float speed = 6f;",
      "    public float gravity = -9.81f;",
      "    private CharacterController controller;",
      "    private Vector3 velocity;",
      "",
      "    void Awake()",
      "    {",
      "        controller = GetComponent<CharacterController>();",
      "    }",
      "",
      "    void Update()",
      "    {",
      "        if (controller.isGrounded && velocity.y < 0)",
      "        {",
      "            velocity.y = -2f;",
      "        }",
      "",
      "        Vector3 input = new Vector3(Input.GetAxis(\"Horizontal\"), 0, Input.GetAxis(\"Vertical\"));",
      "        controller.Move(input * speed * Time.deltaTime);",
      "",
      "        velocity.y += gravity * Time.deltaTime;",
      "        controller.Move(velocity * Time.deltaTime);",
      "    }",
      "}",
    ],
  },
  {
    id: 14,
    title: "שלב 14 — מצלמה עוקבת אחרי השחקן",
    description: "סקריפט CameraFollow קלאסי עם Vector3.Lerp ב-LateUpdate.",
    lines: [
      "using UnityEngine;",
      "",
      "public class CameraFollow : MonoBehaviour",
      "{",
      "    public Transform target;",
      "    public Vector3 offset = new Vector3(0f, 4f, -6f);",
      "    public float smoothSpeed = 5f;",
      "",
      "    void LateUpdate()",
      "    {",
      "        Vector3 desiredPosition = target.position + offset;",
      "        transform.position = Vector3.Lerp(transform.position, desiredPosition, smoothSpeed * Time.deltaTime);",
      "        transform.LookAt(target);",
      "    }",
      "}",
    ],
  },
  {
    id: 15,
    title: "שלב 15 — בינה מלאכותית של אויב עם NavMesh",
    description: "אויב שרודף את השחקן ועובר בין מצבי אנימציה לפי מרחק.",
    lines: [
      "using UnityEngine;",
      "using UnityEngine.AI;",
      "",
      "public class EnemyChaser : MonoBehaviour",
      "{",
      "    public Transform player;",
      "    public float attackRange = 2f;",
      "    private NavMeshAgent agent;",
      "    private Animator anim;",
      "",
      "    void Awake()",
      "    {",
      "        agent = GetComponent<NavMeshAgent>();",
      "        anim = GetComponent<Animator>();",
      "    }",
      "",
      "    void Update()",
      "    {",
      "        float distance = Vector3.Distance(transform.position, player.position);",
      "        anim.SetFloat(\"Speed\", agent.velocity.magnitude);",
      "",
      "        if (distance <= attackRange)",
      "        {",
      "            agent.isStopped = true;",
      "            anim.SetTrigger(\"Attack\");",
      "        }",
      "        else",
      "        {",
      "            agent.isStopped = false;",
      "            agent.SetDestination(player.position);",
      "        }",
      "    }",
      "}",
    ],
  },
  {
    id: 16,
    title: "שלב 16 — סקריפט שלם: PlayerAnimatorSync",
    description: "סינכרון בין תנועת Rigidbody לפרמטרים של Animator — שילוב מלא של שחקן עם אנימציה.",
    lines: [
      "using UnityEngine;",
      "",
      "[RequireComponent(typeof(Rigidbody), typeof(Animator))]",
      "public class PlayerAnimatorSync : MonoBehaviour",
      "{",
      "    public float speed = 5f;",
      "    public float jumpForce = 8f;",
      "    private Rigidbody rb;",
      "    private Animator anim;",
      "    private bool isGrounded = true;",
      "",
      "    void Awake()",
      "    {",
      "        rb = GetComponent<Rigidbody>();",
      "        anim = GetComponent<Animator>();",
      "    }",
      "",
      "    void Update()",
      "    {",
      "        float h = Input.GetAxis(\"Horizontal\");",
      "        float v = Input.GetAxis(\"Vertical\");",
      "        Vector3 move = new Vector3(h, 0, v) * speed;",
      "        transform.Translate(move * Time.deltaTime, Space.World);",
      "",
      "        anim.SetFloat(\"Speed\", move.magnitude);",
      "        anim.SetBool(\"IsGrounded\", isGrounded);",
      "",
      "        if (isGrounded && Input.GetKeyDown(KeyCode.Space))",
      "        {",
      "            rb.AddForce(Vector3.up * jumpForce, ForceMode.Impulse);",
      "            anim.SetTrigger(\"Jump\");",
      "            isGrounded = false;",
      "        }",
      "    }",
      "",
      "    void OnCollisionEnter(Collision collision)",
      "    {",
      "        if (collision.gameObject.CompareTag(\"Ground\"))",
      "        {",
      "            isGrounded = true;",
      "        }",
      "    }",
      "}",
    ],
  },

  // ── SimplePlayer script ────────────────────────────────────────────────────
  {
    id: 17,
    title: "SimplePlayer 1 — Class & Movement Fields",
    description: "Class declaration with RequireComponent, and every movement serialized field with its role.",
    lines: [
      "using UnityEngine;",
      "",
      "// Requires a Rigidbody2D on the same GameObject — Unity adds one automatically",
      "[RequireComponent(typeof(Rigidbody2D))]",
      "public class SimplePlayer : MonoBehaviour",
      "{",
      "    [Header(\"Movement Settings\")]",
      "    // Impulse force applied every FixedUpdate to accelerate the player",
      "    public float speed = 50f;",
      "",
      "    // Hard cap on horizontal velocity — prevents endless acceleration",
      "    public float maxSpeed = 8f;",
      "",
      "    // How quickly velocity bleeds off when no input is held",
      "    public float deceleration = 10f;",
      "",
      "    // Counter-force multiplier when reversing direction (0 = ice, 1 = instant stop)",
      "    [Range(0f, 1f)]",
      "    public float turnAroundBrake = 0.5f;",
    ],
  },
  {
    id: 18,
    title: "SimplePlayer 2 — Visuals & Slope Fields",
    description: "Serialized fields for sprite rotation, slope grip, and slide physics.",
    lines: [
      "    [Header(\"Visuals & Slopes\")]",
      "    // Root transform of the sprite rig — rotated to align with slope normal",
      "    public Transform visualsRoot;",
      "",
      "    // How fast the sprite tilts to match the ground angle (degrees/second)",
      "    public float rotationSpeed = 10f;",
      "",
      "    [Header(\"Slope Handling\")]",
      "    // Slopes steeper than this angle cause the player to slide, ignoring input",
      "    public float maxSlopeAngle = 45f;",
      "",
      "    // Downhill force applied continuously while sliding on a steep slope",
      "    public float slideForce = 30f;",
      "",
      "    // Terminal velocity reached while sliding — caps speed on infinite slopes",
      "    public float maxSlideSpeed = 12f;",
    ],
  },
  {
    id: 19,
    title: "SimplePlayer 3 — Push/Pull & Component Fields",
    description: "Grab-probe settings, physics collider references, and ground-detection fields.",
    lines: [
      "    [Header(\"Push / Pull (Movable)\")]",
      "    // Only objects on this layer are eligible to be grabbed and pushed",
      "    public LayerMask movableLayer;",
      "",
      "    // Local-space offset (along facing dir) where the circular grab probe is placed",
      "    public Vector2 grabCheckOffset = new Vector2(0.5f, 0.0f);",
      "",
      "    // Radius of the overlap circle used to detect a nearby Movable",
      "    public float grabCheckRadius = 0.4f;",
      "",
      "    // Objects heavier than this mass need a special shell to be pushed",
      "    public float heavyMassThreshold = 3.0f;",
      "",
      "    [Header(\"Components\")]",
      "    // Active collider when walking without a shell",
      "    public Collider2D standingCollider;",
      "",
      "    // Taller/wider collider while carrying a shell — blocks narrow gaps",
      "    public Collider2D withShellCollider;",
      "",
      "    // Round collider used during roll — must sit on this GameObject",
      "    public Collider2D rollingCollider;",
    ],
  },
  {
    id: 20,
    title: "SimplePlayer 4 — Ground Detection & Private Fields",
    description: "Raycast ground-check settings and the private runtime fields used by the physics logic.",
    lines: [
      "    [Header(\"Ground Detection\")]",
      "    // World-space offset from the player center where raycasts begin",
      "    public Vector2 groundCheckOffset = new Vector2(0, 0f);",
      "",
      "    // Horizontal gap between the left and right parallel raycasts",
      "    public float groundCheckWidth = 0.5f;",
      "",
      "    // Length of each downward raycast — must reach the floor from the center",
      "    public float groundCheckDistance = 1.0f;",
      "    public LayerMask groundLayer;",
      "",
      "    private Rigidbody2D rb;",
      "    // Reads horizontal axis and button presses from the input system",
      "    private PlayerInputHandler inputHandler;",
      "    private float moveInputX;",
      "    // Normal vector of the ground surface directly below the player",
      "    private Vector2 surfaceNormal = Vector2.up;",
      "    // Cached so grip logic can zero gravity and restore it correctly",
      "    private float defaultGravityScale = 1f;",
      "    // Physics braking is suspended until this timestamp (used after jumps)",
      "    private float preserveMomentumUntil = 0f;",
      "    // The joint that rigidly locks the player to a grabbed Movable",
      "    private FixedJoint2D grabJoint;",
    ],
  },
  {
    id: 21,
    title: "SimplePlayer 5 — Properties & Awake",
    description: "Read-only properties exposed to other systems, and Awake() initialization.",
    lines: [
      "    // Shell speed multiplier — hidden from Inspector but writable by code",
      "    [HideInInspector] public float currentSpeedMultiplier = 1f;",
      "",
      "    [SerializeField, HideInInspector]",
      "    private bool _isMovementDisabled = false;",
      "",
      "    // Setter also releases any grab when movement is disabled (safety)",
      "    public bool isMovementDisabled",
      "    {",
      "        get => _isMovementDisabled;",
      "        set { _isMovementDisabled = value; if (value) ReleaseGrab(); }",
      "    }",
      "",
      "    // Filters out micro-jitter so the Animator gets a clean 0 when nearly still",
      "    public float CurrentSpeed => Mathf.Abs(rb.linearVelocity.x) < 0.15f ? 0f : Mathf.Abs(rb.linearVelocity.x);",
      "    public bool IsGrounded { get; private set; }",
      "    // True while a FixedJoint2D connects the player to a Movable",
      "    public bool IsGrabbing => grabJoint != null;",
      "    public bool CanPushHeavyObjects { get; set; } = false;",
      "    // Exposes Rigidbody2D to shells without making the private field public",
      "    public Rigidbody2D Rb => rb;",
      "",
      "    private void Awake()",
      "    {",
      "        rb = GetComponent<Rigidbody2D>();",
      "        defaultGravityScale = rb.gravityScale;",
      "        inputHandler = GetComponent<PlayerInputHandler>();",
      "        // Lock physics rotation — all sprite rotation goes through visualsRoot",
      "        rb.freezeRotation = true;",
      "    }",
    ],
  },
  {
    id: 22,
    title: "SimplePlayer 6 — FixedUpdate & Update",
    description: "FixedUpdate drives physics; Update reads input and updates visuals each frame.",
    lines: [
      "    private void FixedUpdate()",
      "    {",
      "        if (!isMovementDisabled)",
      "        {",
      "            HandleMovement();",
      "        }",
      "        else",
      "        {",
      "            // While a shell controls physics, never leave gravity zeroed",
      "            rb.gravityScale = defaultGravityScale;",
      "        }",
      "        // Ground detection runs every physics step regardless of movement state",
      "        HandleGroundDetection();",
      "    }",
      "",
      "    private void Update()",
      "    {",
      "        if (inputHandler != null)",
      "        {",
      "            // Zero input automatically when an external system locks movement",
      "            moveInputX = isMovementDisabled ? 0f : inputHandler.MoveValue.x;",
      "        }",
      "        if (!isMovementDisabled)",
      "        {",
      "            HandleVisualRotation();",
      "        }",
      "    }",
    ],
  },
  {
    id: 23,
    title: "SimplePlayer 7 — HandleMovement: Steep Slope (Case A)",
    description: "When the slope angle exceeds maxSlopeAngle the player loses grip and slides downhill.",
    lines: [
      "    private void HandleMovement()",
      "    {",
      "        // Angle between ground normal and straight up (0 = flat, 90 = wall)",
      "        float slopeAngle = Vector2.Angle(surfaceNormal, Vector2.up);",
      "        bool onSteepSlope = IsGrounded && slopeAngle > maxSlopeAngle;",
      "",
      "        // CASE A: Too steep — player loses grip and slides downhill",
      "        if (onSteepSlope)",
      "        {",
      "            rb.gravityScale = defaultGravityScale;",
      "",
      "            // Slope tangent always forced to point downhill (negative Y)",
      "            Vector2 downSlope = new Vector2(surfaceNormal.y, -surfaceNormal.x).normalized;",
      "            if (downSlope.y > 0) downSlope = -downSlope;",
      "",
      "            rb.AddForce(downSlope * slideForce, ForceMode2D.Force);",
      "",
      "            // Cap slide speed so the player never accelerates forever",
      "            if (rb.linearVelocity.magnitude > maxSlideSpeed)",
      "            {",
      "                rb.linearVelocity = rb.linearVelocity.normalized * maxSlideSpeed;",
      "            }",
      "            return;",
      "        }",
    ],
  },
  {
    id: 24,
    title: "SimplePlayer 8 — HandleMovement: Active Input (Case B)",
    description: "Player is pressing a direction — apply force along the slope and clamp speed.",
    lines: [
      "        float actualMaxSpeed = maxSpeed * currentSpeedMultiplier;",
      "",
      "        // CASE B: Player is pressing a direction on walkable ground or in air",
      "        if (Mathf.Abs(moveInputX) > 0.01f)",
      "        {",
      "            rb.gravityScale = defaultGravityScale;",
      "            Vector2 moveDirection = Vector2.right * Mathf.Sign(moveInputX);",
      "",
      "            if (IsGrounded && surfaceNormal != Vector2.up)",
      "            {",
      "                // Push along the slope tangent so the player hugs the surface",
      "                moveDirection = new Vector2(surfaceNormal.y, -surfaceNormal.x).normalized * Mathf.Sign(moveInputX);",
      "                if (moveInputX < 0 && moveDirection.x > 0) moveDirection *= -1;",
      "                if (moveInputX > 0 && moveDirection.x < 0) moveDirection *= -1;",
      "            }",
      "",
      "            // Anti-skating: brake hard when the player reverses horizontal direction",
      "            float currentVelocityX = rb.linearVelocity.x;",
      "            if (Mathf.Sign(moveInputX) != Mathf.Sign(currentVelocityX) && Mathf.Abs(currentVelocityX) > 0.1f)",
      "            {",
      "                rb.AddForce(Vector2.right * -currentVelocityX * (speed * turnAroundBrake), ForceMode2D.Force);",
      "            }",
      "",
      "            rb.AddForce(moveDirection * speed, ForceMode2D.Force);",
      "",
      "            // Hard-clamp horizontal velocity to actualMaxSpeed",
      "            Vector2 vel = rb.linearVelocity;",
      "            if (Mathf.Abs(vel.x) > actualMaxSpeed)",
      "            {",
      "                vel.x = Mathf.Sign(vel.x) * actualMaxSpeed;",
      "                rb.linearVelocity = vel;",
      "            }",
      "        }",
    ],
  },
  {
    id: 25,
    title: "SimplePlayer 9 — HandleMovement: Grip & Air Damping (Cases C & D)",
    description: "No input while grounded locks the player to the slope; no input in air softly damps drift.",
    lines: [
      "        // CASE C: No input while grounded — grip the slope, prevent sliding",
      "        else if (IsGrounded)",
      "        {",
      "            // An external system (e.g. jump) may request no braking for a moment",
      "            if (Time.time < preserveMomentumUntil)",
      "            {",
      "                rb.gravityScale = defaultGravityScale;",
      "                return;",
      "            }",
      "",
      "            // Zeroing gravity removes the downhill component from physics entirely",
      "            rb.gravityScale = 0f;",
      "",
      "            // Smoothly bleed off leftover momentum so stopping still feels physical",
      "            Vector2 vel = Vector2.Lerp(rb.linearVelocity, Vector2.zero, Time.fixedDeltaTime * deceleration);",
      "            if (vel.magnitude < 0.05f) vel = Vector2.zero;",
      "            rb.linearVelocity = vel;",
      "        }",
      "        // CASE D: No input in the air — restore gravity and gently damp horizontal drift",
      "        else",
      "        {",
      "            rb.gravityScale = defaultGravityScale;",
      "",
      "            Vector2 vel = rb.linearVelocity;",
      "            vel.x = Mathf.Lerp(vel.x, 0, Time.fixedDeltaTime * deceleration);",
      "            if (Mathf.Abs(vel.x) < 0.05f) vel.x = 0;",
      "            rb.linearVelocity = vel;",
      "        }",
      "    }",
    ],
  },
  {
    id: 26,
    title: "SimplePlayer 10 — HandleGroundDetection",
    description: "Three parallel downward raycasts determine IsGrounded and the current surface normal.",
    lines: [
      "    private void HandleGroundDetection()",
      "    {",
      "        Vector2 centerPos = (Vector2)transform.position + groundCheckOffset;",
      "        Vector2 leftPos = centerPos + Vector2.left * (groundCheckWidth / 2f);",
      "        Vector2 rightPos = centerPos + Vector2.right * (groundCheckWidth / 2f);",
      "",
      "        bool foundGround = false;",
      "        // Tracks the single closest ground hit to avoid averaging seam normals",
      "        RaycastHit2D closestHit = new RaycastHit2D();",
      "",
      "        Vector2[] origins = { centerPos, leftPos, rightPos };",
      "        foreach (Vector2 origin in origins)",
      "        {",
      "            // RaycastAll returns every collider hit along the ray",
      "            RaycastHit2D[] hits = Physics2D.RaycastAll(origin, Vector2.down, groundCheckDistance, groundLayer);",
      "            foreach (RaycastHit2D hit in hits)",
      "            {",
      "                // Skip triggers and the player's own colliders",
      "                if (hit.collider.isTrigger || hit.collider.gameObject == gameObject) continue;",
      "                if (!foundGround || hit.distance < closestHit.distance)",
      "                {",
      "                    closestHit = hit;",
      "                }",
      "                foundGround = true;",
      "            }",
      "        }",
      "",
      "        IsGrounded = foundGround;",
      "        // Fall back to Vector2.up when airborne so slope logic stays neutral",
      "        surfaceNormal = foundGround ? closestHit.normal : Vector2.up;",
      "    }",
    ],
  },
  {
    id: 27,
    title: "SimplePlayer 11 — Visual Rotation & Grab System",
    description: "Slope-aligned sprite rotation, momentum preservation, and grab toggle/start/release.",
    lines: [
      "    private void HandleVisualRotation()",
      "    {",
      "        if (visualsRoot == null) return;",
      "        // Build a rotation that aligns the sprite's up-axis with the slope normal",
      "        Quaternion targetRotation = Quaternion.FromToRotation(Vector3.up, surfaceNormal);",
      "        // Slerp so the sprite tilts smoothly instead of snapping at floor seams",
      "        visualsRoot.rotation = Quaternion.Lerp(visualsRoot.rotation, targetRotation, Time.deltaTime * rotationSpeed);",
      "        // Flip sprite — skip while grabbing so the crab doesn't spin when pulling",
      "        if (Mathf.Abs(moveInputX) > 0.01f && grabJoint == null)",
      "        {",
      "            Vector3 scale = visualsRoot.localScale;",
      "            scale.x = Mathf.Abs(scale.x) * Mathf.Sign(moveInputX);",
      "            visualsRoot.localScale = scale;",
      "        }",
      "    }",
      "",
      "    // Call after a jump/dash to prevent braking from cancelling launch velocity",
      "    public void PreserveMomentumFor(float duration)",
      "    {",
      "        preserveMomentumUntil = Time.time + duration;",
      "    }",
      "",
      "    // Toggle: grab if free, release if already holding",
      "    public void ToggleGrab()",
      "    {",
      "        if (grabJoint != null) ReleaseGrab();",
      "        else TryStartGrab();",
      "    }",
      "",
      "    public void TryStartGrab()",
      "    {",
      "        if (isMovementDisabled || grabJoint != null) return;",
      "        Movable targetMovable = FindGrabbableObject();",
      "        if (targetMovable != null)",
      "        {",
      "            Rigidbody2D targetRb = targetMovable.GetComponent<Rigidbody2D>();",
      "            // FixedJoint2D rigidly connects two Rigidbody2Ds at their current world positions",
      "            grabJoint = gameObject.AddComponent<FixedJoint2D>();",
      "            grabJoint.connectedBody = targetRb;",
      "            grabJoint.autoConfigureConnectedAnchor = true;",
      "            grabJoint.enableCollision = true;",
      "        }",
      "    }",
      "",
      "    public void ReleaseGrab()",
      "    {",
      "        if (grabJoint == null) return;",
      "        Destroy(grabJoint);",
      "        grabJoint = null;",
      "    }",
      "",
      "    // Returns true when a Movable is in range and we are not already holding one",
      "    public bool CanGrabObject()",
      "    {",
      "        return FindGrabbableObject() != null && grabJoint == null && !isMovementDisabled;",
      "    }",
    ],
  },
  {
    id: 28,
    title: "SimplePlayer 12 — FindGrabbableObject, Collision & Gizmos",
    description: "Overlap-circle grab probe, shell collision forwarding, and editor debug gizmos.",
    lines: [
      "    // OverlapCircle in front of the player — returns the Movable found, or null",
      "    private Movable FindGrabbableObject()",
      "    {",
      "        // Temporarily enable trigger queries so the grab-handle trigger is detected",
      "        bool originalQueriesHitTriggers = Physics2D.queriesHitTriggers;",
      "        Physics2D.queriesHitTriggers = true;",
      "",
      "        float facingMul = (visualsRoot != null && visualsRoot.localScale.x < 0) ? -1f : 1f;",
      "        Vector2 checkCenter = (Vector2)transform.position + new Vector2(grabCheckOffset.x * facingMul, grabCheckOffset.y);",
      "",
      "        Collider2D[] hits = Physics2D.OverlapCircleAll(checkCenter, grabCheckRadius, movableLayer);",
      "        Physics2D.queriesHitTriggers = originalQueriesHitTriggers;",
      "",
      "        foreach (var hit in hits)",
      "        {",
      "            Movable movable = hit.GetComponentInParent<Movable>();",
      "            // Accept only the dedicated grab-handle trigger, not the main body collider",
      "            if (movable != null && hit == movable.grabHandleTrigger)",
      "            {",
      "                return movable;",
      "            }",
      "        }",
      "        return null;",
      "    }",
      "",
      "    // Forward collision events to the active shell so it can react (e.g. break)",
      "    private void OnCollisionEnter2D(Collision2D collision)",
      "    {",
      "        PlayerShellSystem shellSystem = GetComponent<PlayerShellSystem>();",
      "        if (shellSystem != null && shellSystem.CurrentShell != null)",
      "        {",
      "            shellSystem.CurrentShell.OnPlayerCollision(collision);",
      "        }",
      "    }",
      "",
      "    private void OnDrawGizmos()",
      "    {",
      "        // Red lines = the three downward ground-check raycasts",
      "        Gizmos.color = Color.red;",
      "        Vector2 centerPos = (Vector2)transform.position + groundCheckOffset;",
      "        Vector2 leftPos = centerPos + Vector2.left * (groundCheckWidth / 2f);",
      "        Vector2 rightPos = centerPos + Vector2.right * (groundCheckWidth / 2f);",
      "        Gizmos.DrawLine(centerPos, centerPos + Vector2.down * groundCheckDistance);",
      "        Gizmos.DrawLine(leftPos, leftPos + Vector2.down * groundCheckDistance);",
      "        Gizmos.DrawLine(rightPos, rightPos + Vector2.down * groundCheckDistance);",
      "        // Yellow = grab probe free; Magenta = currently grabbing an object",
      "        Gizmos.color = grabJoint != null ? Color.magenta : Color.yellow;",
      "        float facing = (visualsRoot != null && visualsRoot.localScale.x < 0) ? -1f : 1f;",
      "        Vector2 grabPos = (Vector2)transform.position + new Vector2(grabCheckOffset.x * facing, grabCheckOffset.y);",
      "        Gizmos.DrawWireSphere(grabPos, grabCheckRadius);",
      "    }",
      "}",
    ],
  },

  // ── Unity API Examples ─────────────────────────────────────────────────────
  {
    id: 29,
    title: "Unity API — Rigidbody",
    description: "AddForce modes, velocity clamping, MovePosition, and constraints from the Unity ScriptReference.",
    lines: [
      "using UnityEngine;",
      "",
      "// Rigidbody: drives all physics-based movement — always use FixedUpdate",
      "public class RigidbodyAPI : MonoBehaviour",
      "{",
      "    public float thrust = 10f;",
      "    private Rigidbody rb;",
      "",
      "    void Start()",
      "    {",
      "        rb = GetComponent<Rigidbody>();",
      "    }",
      "",
      "    void FixedUpdate()",
      "    {",
      "        // Force: continuous push scaled by mass each physics step",
      "        rb.AddForce(Vector3.forward * thrust, ForceMode.Force);",
      "",
      "        // Impulse: instant kick — ignores mass, like a jump or explosion",
      "        rb.AddForce(Vector3.up * 8f, ForceMode.Impulse);",
      "",
      "        // VelocityChange: instant velocity delta that ignores mass",
      "        rb.AddForce(Vector3.right * 3f, ForceMode.VelocityChange);",
      "",
      "        // Clamp horizontal speed without touching vertical (gravity)",
      "        Vector3 vel = rb.linearVelocity;",
      "        vel.x = Mathf.Clamp(vel.x, -5f, 5f);",
      "        rb.linearVelocity = vel;",
      "",
      "        // MovePosition: kinematic-safe teleport that respects interpolation",
      "        rb.MovePosition(rb.position + Vector3.forward * Time.fixedDeltaTime);",
      "",
      "        // Freeze rotation axes so physics never tips the character over",
      "        rb.constraints = RigidbodyConstraints.FreezeRotationX |",
      "                         RigidbodyConstraints.FreezeRotationZ;",
      "    }",
      "}",
    ],
  },
  {
    id: 30,
    title: "Unity API — Physics.Raycast",
    description: "Single ray, layer mask, SphereCast and the full RaycastHit data from the Unity ScriptReference.",
    lines: [
      "using UnityEngine;",
      "",
      "public class RaycastAPI : MonoBehaviour",
      "{",
      "    void Update()",
      "    {",
      "        // Layer mask — bit-shift to select only layer 8",
      "        int layerMask = 1 << 8;",
      "",
      "        RaycastHit hit;",
      "        // Cast from this object forward; Mathf.Infinity = no distance limit",
      "        if (Physics.Raycast(transform.position, transform.forward, out hit, Mathf.Infinity, layerMask))",
      "        {",
      "            // hit.point   — world-space contact position",
      "            // hit.normal  — surface normal at the contact point",
      "            // hit.distance— distance along the ray to the hit",
      "            Debug.DrawRay(transform.position, transform.forward * hit.distance, Color.yellow);",
      "            Debug.Log(\"Hit: \" + hit.collider.name + \" dist: \" + hit.distance);",
      "        }",
      "",
      "        // SphereCast: like Raycast but with a radius — good for wide characters",
      "        RaycastHit sphereHit;",
      "        if (Physics.SphereCast(transform.position, 0.5f, transform.forward, out sphereHit, 10f))",
      "        {",
      "            Debug.Log(\"SphereCast hit: \" + sphereHit.transform.name);",
      "        }",
      "",
      "        // RaycastAll: returns every collider hit, not just the closest",
      "        RaycastHit[] hits = Physics.RaycastAll(transform.position, transform.forward, 100f);",
      "        foreach (RaycastHit h in hits)",
      "        {",
      "            Debug.Log(h.collider.name);",
      "        }",
      "    }",
      "}",
    ],
  },
  {
    id: 31,
    title: "Unity API — Vector3",
    description: "Lerp, MoveTowards, Distance, Dot, Cross and Reflect — the most-used Vector3 statics.",
    lines: [
      "using UnityEngine;",
      "",
      "public class Vector3API : MonoBehaviour",
      "{",
      "    public Transform target;",
      "    public float speed = 5f;",
      "",
      "    void Update()",
      "    {",
      "        // Lerp: interpolate by fraction t (0..1) — smooth but slows near target",
      "        transform.position = Vector3.Lerp(transform.position, target.position, speed * Time.deltaTime);",
      "",
      "        // MoveTowards: constant speed, guaranteed to stop at target",
      "        float step = speed * Time.deltaTime;",
      "        transform.position = Vector3.MoveTowards(transform.position, target.position, step);",
      "",
      "        // Distance: magnitude of (b - a)",
      "        float dist = Vector3.Distance(transform.position, target.position);",
      "",
      "        // Dot: > 0 same dir, 0 perpendicular, < 0 opposite — use for facing checks",
      "        float dot = Vector3.Dot(transform.forward, (target.position - transform.position).normalized);",
      "        bool isFacing = dot > 0.5f;",
      "",
      "        // Cross: perpendicular vector following the right-hand rule",
      "        Vector3 perp = Vector3.Cross(transform.forward, transform.right);",
      "",
      "        // Reflect: bounce direction off a surface defined by a normal",
      "        Vector3 bounced = Vector3.Reflect(transform.forward, Vector3.up);",
      "",
      "        // Project: flatten a vector onto a plane (remove vertical component)",
      "        Vector3 flatDir = Vector3.ProjectOnPlane(transform.forward, Vector3.up);",
      "    }",
      "}",
    ],
  },
  {
    id: 32,
    title: "Unity API — Quaternion",
    description: "Euler, LookRotation, Slerp, RotateTowards, AngleAxis and Angle from the Unity ScriptReference.",
    lines: [
      "using UnityEngine;",
      "",
      "public class QuaternionAPI : MonoBehaviour",
      "{",
      "    public Transform target;",
      "    public float rotSpeed = 90f;",
      "",
      "    void Update()",
      "    {",
      "        // Euler: create a rotation from X/Y/Z degrees (applied Z, X, Y order)",
      "        transform.rotation = Quaternion.Euler(0f, 180f, 0f);",
      "",
      "        // LookRotation: face the given forward direction (up defaults to world up)",
      "        Vector3 direction = (target.position - transform.position).normalized;",
      "        Quaternion lookRot = Quaternion.LookRotation(direction);",
      "",
      "        // Slerp: smooth arc interpolation — t=0 is from, t=1 is to",
      "        transform.rotation = Quaternion.Slerp(transform.rotation, lookRot, rotSpeed * Time.deltaTime);",
      "",
      "        // RotateTowards: constant angular speed, never overshoots",
      "        float step = rotSpeed * Time.deltaTime;",
      "        transform.rotation = Quaternion.RotateTowards(transform.rotation, lookRot, step);",
      "",
      "        // AngleAxis: rotate by angle degrees around an arbitrary axis",
      "        transform.rotation = Quaternion.AngleAxis(45f, Vector3.up);",
      "",
      "        // Angle: degrees between two rotations (useful for aim tolerance checks)",
      "        float angleDiff = Quaternion.Angle(transform.rotation, lookRot);",
      "        bool isAligned = angleDiff < 10f;",
      "    }",
      "}",
    ],
  },
  {
    id: 33,
    title: "Unity API — Coroutines & Yield",
    description: "WaitForSeconds, WaitUntil, WaitForEndOfFrame, WaitForFixedUpdate and stopping coroutines.",
    lines: [
      "using UnityEngine;",
      "using System.Collections;",
      "",
      "public class CoroutineAPI : MonoBehaviour",
      "{",
      "    private Coroutine spawnRoutine;",
      "",
      "    void Start()",
      "    {",
      "        // StartCoroutine returns a handle you can use to stop it later",
      "        spawnRoutine = StartCoroutine(SpawnLoop());",
      "    }",
      "",
      "    // yield return suspends execution; the method resumes on the next matching frame",
      "    IEnumerator SpawnLoop()",
      "    {",
      "        while (true)",
      "        {",
      "            SpawnEnemy();",
      "            // Pause for 3 real seconds before spawning the next one",
      "            yield return new WaitForSeconds(3f);",
      "        }",
      "    }",
      "",
      "    IEnumerator WaitForInput()",
      "    {",
      "        // Suspend until a delegate returns true — checked once per frame",
      "        yield return new WaitUntil(() => Input.GetKeyDown(KeyCode.Space));",
      "        Debug.Log(\"Space pressed!\");",
      "    }",
      "",
      "    IEnumerator EndOfFrameWork()",
      "    {",
      "        // Resume after all cameras have rendered — useful for screenshot logic",
      "        yield return new WaitForEndOfFrame();",
      "        // Resume at the start of the next FixedUpdate step",
      "        yield return new WaitForFixedUpdate();",
      "        // Resume next Update (single null yield = one frame skip)",
      "        yield return null;",
      "    }",
      "",
      "    void Stop() { StopCoroutine(spawnRoutine); }",
      "    void SpawnEnemy() { Debug.Log(\"Spawned at \" + Time.time); }",
      "}",
    ],
  },
  {
    id: 34,
    title: "Unity API — ScriptableObject",
    description: "CreateAssetMenu, data asset pattern, and loading assets at runtime via Resources.",
    lines: [
      "using UnityEngine;",
      "",
      "// CreateAssetMenu adds a right-click menu item in the Project window",
      "[CreateAssetMenu(fileName = \"NewItem\", menuName = \"Game/Item Data\", order = 1)]",
      "public class ItemData : ScriptableObject",
      "{",
      "    [Header(\"Stats\")]",
      "    public string itemName = \"Sword\";",
      "    public int damage = 10;",
      "    public float cooldown = 0.5f;",
      "    public Sprite icon;",
      "",
      "    // ScriptableObjects can contain logic, not just data",
      "    public bool CanAfford(int playerGold) => playerGold >= damage * 10;",
      "}",
      "",
      "// ── Consumer MonoBehaviour ─────────────────────────────────────────",
      "public class PlayerInventory : MonoBehaviour",
      "{",
      "    // Drag the .asset file from the Project window into this field",
      "    public ItemData equippedItem;",
      "",
      "    void UseItem()",
      "    {",
      "        Debug.Log(\"Using: \" + equippedItem.itemName + \" dmg: \" + equippedItem.damage);",
      "    }",
      "",
      "    void LoadFromResources()",
      "    {",
      "        // Load an asset placed under Assets/Resources/ at runtime",
      "        ItemData sword = Resources.Load<ItemData>(\"Items/Sword\");",
      "    }",
      "}",
    ],
  },
  {
    id: 35,
    title: "Unity API — Camera Utilities",
    description: "ScreenPointToRay for mouse picking, ViewportToWorldPoint, WorldToScreenPoint, and field-of-view.",
    lines: [
      "using UnityEngine;",
      "",
      "public class CameraAPI : MonoBehaviour",
      "{",
      "    public Transform target;",
      "",
      "    void Update()",
      "    {",
      "        // Build a Ray from the camera through the mouse cursor",
      "        Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);",
      "        RaycastHit hit;",
      "        if (Physics.Raycast(ray, out hit))",
      "        {",
      "            // hit.point is the 3D world position under the cursor",
      "            Debug.DrawLine(ray.origin, hit.point, Color.cyan);",
      "        }",
      "",
      "        // ViewportToWorldPoint: (0..1, 0..1, depth)",
      "        // Center of screen, 10 units in front of the camera",
      "        Vector3 center = Camera.main.ViewportToWorldPoint(new Vector3(0.5f, 0.5f, 10f));",
      "",
      "        // WorldToScreenPoint: convert a world position to pixel coordinates",
      "        Vector3 screenPos = Camera.main.WorldToScreenPoint(target.position);",
      "        bool isOnScreen = screenPos.z > 0 &&",
      "                          screenPos.x > 0 && screenPos.x < Screen.width &&",
      "                          screenPos.y > 0 && screenPos.y < Screen.height;",
      "",
      "        // Smoothly zoom the field of view",
      "        float targetFov = Input.GetKey(KeyCode.Z) ? 30f : 60f;",
      "        Camera.main.fieldOfView = Mathf.Lerp(Camera.main.fieldOfView, targetFov, Time.deltaTime * 5f);",
      "    }",
      "}",
    ],
  },
  {
    id: 36,
    title: "Unity API — Events & Delegates",
    description: "UnityEvent, UnityEvent<T>, System.Action with subscribe/unsubscribe pattern and null-safe invoke.",
    lines: [
      "using UnityEngine;",
      "using UnityEngine.Events;",
      "using System;",
      "",
      "public class EventsAPI : MonoBehaviour",
      "{",
      "    // UnityEvent: wired in the Inspector without code — zero-argument version",
      "    public UnityEvent onPlayerDied;",
      "",
      "    // UnityEvent<T>: passes one argument to every Inspector and code listener",
      "    public UnityEvent<int> onScoreChanged;",
      "",
      "    // System.Action: lightweight C# delegate — no Inspector support",
      "    public static event Action<GameObject> OnEnemySpawned;",
      "",
      "    void Die()",
      "    {",
      "        // ?.Invoke() is null-safe: does nothing if no listeners are wired up",
      "        onPlayerDied?.Invoke();",
      "        onScoreChanged?.Invoke(0);",
      "        OnEnemySpawned?.Invoke(gameObject);",
      "    }",
      "",
      "    void OnEnable()",
      "    {",
      "        // Subscribe with += — executed every time the event fires",
      "        OnEnemySpawned += HandleEnemySpawned;",
      "    }",
      "",
      "    void OnDisable()",
      "    {",
      "        // Always unsubscribe in OnDisable — prevents memory leaks and ghost calls",
      "        OnEnemySpawned -= HandleEnemySpawned;",
      "    }",
      "",
      "    void HandleEnemySpawned(GameObject enemy)",
      "    {",
      "        Debug.Log(\"Enemy spawned: \" + enemy.name);",
      "    }",
      "}",
    ],
  },
  {
    id: 37,
    title: "Unity API — Invoke & InvokeRepeating",
    description: "Invoke, InvokeRepeating, CancelInvoke and IsInvoking — Unity's built-in delayed-call system.",
    lines: [
      "using UnityEngine;",
      "",
      "public class InvokeAPI : MonoBehaviour",
      "{",
      "    void Start()",
      "    {",
      "        // Invoke: call a method by name after 'delay' seconds (fire-and-forget)",
      "        Invoke(\"SpawnEnemy\", 2f);",
      "",
      "        // InvokeRepeating: call after 'delay', then every 'repeatRate' seconds",
      "        InvokeRepeating(\"SpawnEnemy\", 2f, 1f);",
      "    }",
      "",
      "    void SpawnEnemy()",
      "    {",
      "        Debug.Log(\"Spawned at \" + Time.time);",
      "    }",
      "",
      "    void StopSpawning()",
      "    {",
      "        // Cancel a specific pending Invoke on this MonoBehaviour",
      "        CancelInvoke(\"SpawnEnemy\");",
      "",
      "        // Cancel ALL pending Invokes on this MonoBehaviour",
      "        CancelInvoke();",
      "    }",
      "",
      "    void Update()",
      "    {",
      "        // IsInvoking: true when a matching Invoke is currently scheduled",
      "        if (!IsInvoking(\"SpawnEnemy\"))",
      "        {",
      "            InvokeRepeating(\"SpawnEnemy\", 0f, 1f);",
      "        }",
      "    }",
      "}",
    ],
  },
  {
    id: 38,
    title: "Unity API — Instantiate, Destroy & Object Pooling",
    description: "Instantiate overloads, Destroy timing, DontDestroyOnLoad and basic manual object pooling.",
    lines: [
      "using UnityEngine;",
      "using System.Collections.Generic;",
      "",
      "public class SpawnAPI : MonoBehaviour",
      "{",
      "    public GameObject prefab;",
      "    public Transform spawnPoint;",
      "",
      "    void Spawn()",
      "    {",
      "        // Clone prefab at an explicit position and rotation",
      "        GameObject obj = Instantiate(prefab, spawnPoint.position, spawnPoint.rotation);",
      "",
      "        // Parent to a container to keep the hierarchy tidy",
      "        obj.transform.SetParent(transform);",
      "",
      "        // Destroy after 5 seconds — the delay is world-time, not frame count",
      "        Destroy(obj, 5f);",
      "    }",
      "",
      "    void SpawnAsChild()",
      "    {",
      "        // Third overload parents immediately, preserving world position",
      "        Instantiate(prefab, spawnPoint);",
      "    }",
      "",
      "    // Manual pool: reuse objects instead of Instantiate/Destroy each time",
      "    private Queue<GameObject> pool = new Queue<GameObject>();",
      "",
      "    GameObject GetFromPool()",
      "    {",
      "        if (pool.Count > 0)",
      "        {",
      "            GameObject obj = pool.Dequeue();",
      "            obj.SetActive(true);",
      "            return obj;",
      "        }",
      "        return Instantiate(prefab);",
      "    }",
      "",
      "    void ReturnToPool(GameObject obj)",
      "    {",
      "        obj.SetActive(false);",
      "        pool.Enqueue(obj);",
      "    }",
      "}",
    ],
  },
];
