// Lesson curriculum: progressive C# / Unity MonoBehaviour typing course.
// Each lesson has a title, a Hebrew description, and an array of code lines to type.
// Lines preserve real indentation (4 spaces per level) so muscle memory transfers to a real IDE.

const LESSONS = [
  {
    id: 1,
    title: "שלב 1 — סימני פיסוק וסוגריים",
    description: "התרגלות לסימנים הנפוצים ביותר בקוד C#: סוגריים, נקודה-פסיק, נקודה.",
    lines: [
      "{ }",
      "( )",
      "[ ]",
      "< >",
      ";",
      "{ ; }",
      "( ) { }",
      "a.b.c;",
      "x = 1;",
      "x == 1;",
      "x != 1;",
      "x += 1;",
      "x -= 1;",
      "x++;",
      "x--;",
      "a && b;",
      "a || b;",
      "!a;",
    ],
  },
  {
    id: 2,
    title: "שלב 2 — משתנים וטיפוסים",
    description: "הצהרות משתנים בסיסיות עם הטיפוסים הנפוצים ב-C#.",
    lines: [
      "int health = 100;",
      "float speed = 5.0f;",
      "bool isAlive = true;",
      "string playerName = \"Zion\";",
      "var score = 0;",
      "double gravity = 9.81;",
      "const int maxLives = 3;",
      "private int ammoCount = 30;",
      "public float jumpForce = 8f;",
      "[SerializeField] private int level;",
    ],
  },
  {
    id: 3,
    title: "שלב 3 — שלד של MonoBehaviour",
    description: "המבנה הבסיסי של כל סקריפט ביוניטי.",
    lines: [
      "using UnityEngine;",
      "",
      "public class PlayerController : MonoBehaviour",
      "{",
      "    void Start()",
      "    {",
      "    }",
      "",
      "    void Update()",
      "    {",
      "    }",
      "}",
    ],
  },
  {
    id: 4,
    title: "שלב 4 — מתודות מחזור החיים של יוניטי",
    description: "Awake, Start, Update, FixedUpdate ועוד — בסדר הנכון.",
    lines: [
      "void Awake()",
      "{",
      "    Debug.Log(\"Awake called\");",
      "}",
      "",
      "void OnEnable()",
      "{",
      "}",
      "",
      "void Start()",
      "{",
      "}",
      "",
      "void FixedUpdate()",
      "{",
      "}",
      "",
      "void LateUpdate()",
      "{",
      "}",
      "",
      "void OnDisable()",
      "{",
      "}",
      "",
      "void OnDestroy()",
      "{",
      "}",
    ],
  },
  {
    id: 5,
    title: "שלב 5 — Transform ו-Vector3",
    description: "תנועה בסיסית של אובייקטים במרחב התלת-מימדי.",
    lines: [
      "transform.position = Vector3.zero;",
      "transform.position += Vector3.forward;",
      "transform.Translate(Vector3.up * speed);",
      "transform.rotation = Quaternion.identity;",
      "transform.Rotate(0f, 90f, 0f);",
      "Vector3 direction = new Vector3(1, 0, 0);",
      "transform.localScale = Vector3.one * 2f;",
      "transform.LookAt(target);",
    ],
  },
  {
    id: 6,
    title: "שלב 6 — קלט מהשחקן (Input)",
    description: "קריאת מקשים, צירים ולחיצות עכבר.",
    lines: [
      "float h = Input.GetAxis(\"Horizontal\");",
      "float v = Input.GetAxis(\"Vertical\");",
      "if (Input.GetKeyDown(KeyCode.Space))",
      "{",
      "    Jump();",
      "}",
      "if (Input.GetMouseButtonDown(0))",
      "{",
      "    Shoot();",
      "}",
      "Vector3 move = new Vector3(h, 0, v) * speed * Time.deltaTime;",
    ],
  },
  {
    id: 7,
    title: "שלב 7 — GetComponent ורכיבים",
    description: "גישה לרכיבים אחרים על אותו GameObject.",
    lines: [
      "Rigidbody rb = GetComponent<Rigidbody>();",
      "Animator anim = GetComponent<Animator>();",
      "rb.AddForce(Vector3.up * jumpForce, ForceMode.Impulse);",
      "anim.SetBool(\"isRunning\", true);",
      "anim.SetTrigger(\"Attack\");",
      "if (TryGetComponent<Collider>(out Collider col))",
      "{",
      "    col.enabled = false;",
      "}",
    ],
  },
  {
    id: 8,
    title: "שלב 8 — פיזיקה והתנגשויות",
    description: "OnCollisionEnter, OnTriggerEnter ועבודה עם תגיות.",
    lines: [
      "void OnTriggerEnter(Collider other)",
      "{",
      "    if (other.CompareTag(\"Enemy\"))",
      "    {",
      "        TakeDamage(10);",
      "    }",
      "}",
      "",
      "void OnCollisionEnter(Collision collision)",
      "{",
      "    Debug.Log(collision.gameObject.name);",
      "}",
    ],
  },
  {
    id: 9,
    title: "שלב 9 — Coroutines",
    description: "פעולות אסינכרוניות מבוססות זמן בסטייל יוניטי.",
    lines: [
      "IEnumerator RespawnAfterDelay(float delay)",
      "{",
      "    yield return new WaitForSeconds(delay);",
      "    gameObject.SetActive(true);",
      "}",
      "",
      "void Die()",
      "{",
      "    StartCoroutine(RespawnAfterDelay(3f));",
      "}",
    ],
  },
  {
    id: 10,
    title: "שלב 10 — סקריפט שלם: PlayerController",
    description: "כתיבת סקריפט מלא של תנועת שחקן ב-Unity.",
    lines: [
      "using UnityEngine;",
      "",
      "public class PlayerController : MonoBehaviour",
      "{",
      "    public float speed = 5f;",
      "    public float jumpForce = 8f;",
      "    private Rigidbody rb;",
      "",
      "    void Awake()",
      "    {",
      "        rb = GetComponent<Rigidbody>();",
      "    }",
      "",
      "    void Update()",
      "    {",
      "        float h = Input.GetAxis(\"Horizontal\");",
      "        float v = Input.GetAxis(\"Vertical\");",
      "        Vector3 move = new Vector3(h, 0, v) * speed;",
      "        transform.Translate(move * Time.deltaTime);",
      "",
      "        if (Input.GetKeyDown(KeyCode.Space))",
      "        {",
      "            rb.AddForce(Vector3.up * jumpForce, ForceMode.Impulse);",
      "        }",
      "    }",
      "}",
    ],
  },
  {
    id: 11,
    title: "שלב 11 — סקריפט שלם: Health & Enemy",
    description: "מערכת חיים, נזק ומוות עם אירועים.",
    lines: [
      "using UnityEngine;",
      "using System;",
      "",
      "public class Health : MonoBehaviour",
      "{",
      "    public int maxHealth = 100;",
      "    private int currentHealth;",
      "    public event Action OnDeath;",
      "",
      "    void Start()",
      "    {",
      "        currentHealth = maxHealth;",
      "    }",
      "",
      "    public void TakeDamage(int amount)",
      "    {",
      "        currentHealth -= amount;",
      "        if (currentHealth <= 0)",
      "        {",
      "            OnDeath?.Invoke();",
      "            Destroy(gameObject);",
      "        }",
      "    }",
      "}",
    ],
  },
  {
    id: 12,
    title: "שלב 12 — Animator מתקדם",
    description: "פרמטרים של Animator: SetFloat, CrossFade ואירועי אנימציה.",
    lines: [
      "anim.SetFloat(\"Speed\", currentSpeed);",
      "anim.SetFloat(\"Speed\", currentSpeed, 0.1f, Time.deltaTime);",
      "anim.SetBool(\"IsGrounded\", isGrounded);",
      "anim.SetInteger(\"ComboIndex\", comboIndex);",
      "anim.CrossFade(\"Attack\", 0.15f);",
      "anim.Play(\"Idle\", 0);",
      "if (anim.GetCurrentAnimatorStateInfo(0).IsName(\"Jump\"))",
      "{",
      "    anim.applyRootMotion = true;",
      "}",
      "",
      "void OnFootstep(AnimationEvent evt)",
      "{",
      "    AudioSource.PlayClipAtPoint(footstepClip, transform.position);",
      "}",
    ],
  },
  {
    id: 13,
    title: "שלב 13 — CharacterController",
    description: "תנועה מבוססת קפסולה עם בדיקת קרקע וכבידה.",
    lines: [
      "using UnityEngine;",
      "",
      "[RequireComponent(typeof(CharacterController))]",
      "public class PlayerMotor : MonoBehaviour",
      "{",
      "    public float speed = 6f;",
      "    public float gravity = -9.81f;",
      "    private CharacterController controller;",
      "    private Vector3 velocity;",
      "",
      "    void Awake()",
      "    {",
      "        controller = GetComponent<CharacterController>();",
      "    }",
      "",
      "    void Update()",
      "    {",
      "        if (controller.isGrounded && velocity.y < 0)",
      "        {",
      "            velocity.y = -2f;",
      "        }",
      "",
      "        Vector3 input = new Vector3(Input.GetAxis(\"Horizontal\"), 0, Input.GetAxis(\"Vertical\"));",
      "        controller.Move(input * speed * Time.deltaTime);",
      "",
      "        velocity.y += gravity * Time.deltaTime;",
      "        controller.Move(velocity * Time.deltaTime);",
      "    }",
      "}",
    ],
  },
  {
    id: 14,
    title: "שלב 14 — מצלמה עוקבת אחרי השחקן",
    description: "סקריפט CameraFollow קלאסי עם Vector3.Lerp ב-LateUpdate.",
    lines: [
      "using UnityEngine;",
      "",
      "public class CameraFollow : MonoBehaviour",
      "{",
      "    public Transform target;",
      "    public Vector3 offset = new Vector3(0f, 4f, -6f);",
      "    public float smoothSpeed = 5f;",
      "",
      "    void LateUpdate()",
      "    {",
      "        Vector3 desiredPosition = target.position + offset;",
      "        transform.position = Vector3.Lerp(transform.position, desiredPosition, smoothSpeed * Time.deltaTime);",
      "        transform.LookAt(target);",
      "    }",
      "}",
    ],
  },
  {
    id: 15,
    title: "שלב 15 — בינה מלאכותית של אויב עם NavMesh",
    description: "אויב שרודף את השחקן ועובר בין מצבי אנימציה לפי מרחק.",
    lines: [
      "using UnityEngine;",
      "using UnityEngine.AI;",
      "",
      "public class EnemyChaser : MonoBehaviour",
      "{",
      "    public Transform player;",
      "    public float attackRange = 2f;",
      "    private NavMeshAgent agent;",
      "    private Animator anim;",
      "",
      "    void Awake()",
      "    {",
      "        agent = GetComponent<NavMeshAgent>();",
      "        anim = GetComponent<Animator>();",
      "    }",
      "",
      "    void Update()",
      "    {",
      "        float distance = Vector3.Distance(transform.position, player.position);",
      "        anim.SetFloat(\"Speed\", agent.velocity.magnitude);",
      "",
      "        if (distance <= attackRange)",
      "        {",
      "            agent.isStopped = true;",
      "            anim.SetTrigger(\"Attack\");",
      "        }",
      "        else",
      "        {",
      "            agent.isStopped = false;",
      "            agent.SetDestination(player.position);",
      "        }",
      "    }",
      "}",
    ],
  },
  {
    id: 16,
    title: "שלב 16 — סקריפט שלם: PlayerAnimatorSync",
    description: "סינכרון בין תנועת Rigidbody לפרמטרים של Animator — שילוב מלא של שחקן עם אנימציה.",
    lines: [
      "using UnityEngine;",
      "",
      "[RequireComponent(typeof(Rigidbody), typeof(Animator))]",
      "public class PlayerAnimatorSync : MonoBehaviour",
      "{",
      "    public float speed = 5f;",
      "    public float jumpForce = 8f;",
      "    private Rigidbody rb;",
      "    private Animator anim;",
      "    private bool isGrounded = true;",
      "",
      "    void Awake()",
      "    {",
      "        rb = GetComponent<Rigidbody>();",
      "        anim = GetComponent<Animator>();",
      "    }",
      "",
      "    void Update()",
      "    {",
      "        float h = Input.GetAxis(\"Horizontal\");",
      "        float v = Input.GetAxis(\"Vertical\");",
      "        Vector3 move = new Vector3(h, 0, v) * speed;",
      "        transform.Translate(move * Time.deltaTime, Space.World);",
      "",
      "        anim.SetFloat(\"Speed\", move.magnitude);",
      "        anim.SetBool(\"IsGrounded\", isGrounded);",
      "",
      "        if (isGrounded && Input.GetKeyDown(KeyCode.Space))",
      "        {",
      "            rb.AddForce(Vector3.up * jumpForce, ForceMode.Impulse);",
      "            anim.SetTrigger(\"Jump\");",
      "            isGrounded = false;",
      "        }",
      "    }",
      "",
      "    void OnCollisionEnter(Collision collision)",
      "    {",
      "        if (collision.gameObject.CompareTag(\"Ground\"))",
      "        {",
      "            isGrounded = true;",
      "        }",
      "    }",
      "}",
    ],
  },
];
